global_frame: /map
robot_base_frame: base_footprint
update_frequency: 1.0
publish_frequency: 1.0

# publish_voxel_map: true
# 
# map_type: voxel
# origin_z: 0.0
# z_resolution: 0.2
# z_voxels: 10
# unknown_threshold: 10
# mark_threshold: 0
# 
obstacle_range: 4.5
raytrace_range: 4.0

footprint: [[0.4,0.4],[0.4,-0.4],[-0.3,-0.4],[-0.3,0.4]]
footprint_padding: 0.05

#footprint: [0.4,0.5,0.4,-0.5,-0.3,-0.5,-0.3,0.5]

inflater:
  inflation_radius: 1.7
  cost_scaling_factor: 14.0


laserobstacles:
  observation_sources: scan scan_rear
  scan: {data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
  scan_rear: {data_type: LaserScan, topic: scan_filtered_rear, marking: true, clearing: true}
  marking: true
  clearing: true

kinectobstacles:
  observation_sources: pointcloud_sensor_in pointcloud_sensor_clear
  pointcloud_sensor_in:
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    min_obstacle_height: 0.6
    max_obstacle_height: 1.3
    z_voxels: 8
    z_resolution: 0.25
    marking: true
    clearing: false
    observation_persistence: 0.0
    obstacle_range: 2.0
    raytrace_range: 2.0
  pointcloud_sensor_clear:
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0
    z_voxels: 8
    z_resolution: 0.25
    marking: false
    clearing: true
    observation_persistence: 0.0
    obstacle_range: 2.5
    raytrace_range: 2.5
