global_costmap:
   robot_base_frame: base_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   transform_tolerance: 0.5
   plugins:
     - {name: static_map, type: "costmap_2d::StaticLayer"}
     - {name: laserobstacles, type: "costmap_2d::VoxelLayer"}
     - {name: kinectobstacles, type: "costmap_2d::VoxelLayer"}
     - {name: inflater, type: "costmap_2d::InflationLayer"}
